#!/usr/bin/env python3

import pysolr
import json
from time import sleep

def iter_records(solr, **qparams):
    result = solr.search(**qparams)

    while True:
        for doc in result.docs:
            yield doc
        if result.raw_response['responseHeader']['params'].get('cursorMark',None) == result.raw_response.get("nextCursorMark",None):
            break
        qparams['cursorMark']=result.raw_response["nextCursorMark"]
        result = solr.search(**qparams)

solr = pysolr.Solr('http://pnt-cee-solr.corp.redhat.com/solr/access')

print('[')

first=True
for rec in iter_records(solr,
   wt="json",
   q="documentKind:Solution", 
   # fq=["caseCount_365:[1 TO *]","lastModifiedDate:[NOW-2MONTHS TO NOW]"],
   fq="caseCount_365:[1 TO *]",
   fl='solution.id,tag,product,accessState,duplicateResourceId,language,body,issue',
   sort='solution.id asc,uri asc',
   cursorMark='*'
   ):
   first or print(',')
   first=False
   print(json.dumps(rec, indent=4))
   sleep(.1)

print(']')
